# Generated by Django 2.2.12 on 2020-05-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200519_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='uuid',
            new_name='id',
        ),
    ]
